// <auto-generated />
using System;
using HRMS_WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMS_WebApi.Migrations
{
    [DbContext(typeof(HrmsContext))]
    [Migration("20200412071236_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRMS_WebApi.Models.Menu", b =>
                {
                    b.Property<string>("MenuID")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("ControllerID")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("MenuGroup")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MenuNameEng")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MenuNameTh")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("MenuID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("HRMS_WebApi.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("RoleName")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("HRMS_WebApi.Models.RoleMenu", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("MenuId")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenu");
                });

            modelBuilder.Entity("HRMS_WebApi.Models.Site", b =>
                {
                    b.Property<string>("SiteId")
                        .HasColumnType("varchar(3)");

                    b.Property<byte>("BillDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("CustomerCode")
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("ExtendTime")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LoginLockTimes")
                        .HasColumnType("tinyint");

                    b.Property<string>("SiteName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("WarningMessage")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("WarningTimes")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("SiteId");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("HRMS_WebApi.Models.RoleMenu", b =>
                {
                    b.HasOne("HRMS_WebApi.Models.Menu", "Menu")
                        .WithMany("RoleMenu")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMS_WebApi.Models.Role", "Role")
                        .WithMany("RoleMenu")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
